services:
  postgresdb:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=st_bank
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_DRIVER=postgres
      - DB_SOURCE=postgresql://root:password@postgresdb:5432/st_bank?sslmode=disable
      - SERVER_ADDRESS=0.0.0.0:8080
      - TOKEN_SYMMETRIC_KEY=12345678901234567890123456789012
      - ACCESS_TOKEN_DURATION=15m
      - TOKEN_TYPE=paseto
    depends_on:
      - postgresdb

volumes:
  postgres_data:
